$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:2
        },
         900:{
            items:3
        },
         1150:{
            items:4
        },
         1400:{
            items:5
        },
        1700:{
            items:6
        }
    }
})